import {Dimensions, Platform, StatusBar} from 'react-native';
import DeviceUiInfo from '@src/utils/DeviceInfo';

const {width, height} = Dimensions.get('window');
const statusBarHeight = StatusBar.currentHeight || 0;

// Used via Metrics.baseMargin
const metrics = {
  tabletListColumn: 3,
  tabletWidth: '60%',
  tabletModalWidth: '70%',
  marginHorizontal: DeviceUiInfo.moderateScale(10),
  marginVertical: DeviceUiInfo.moderateScale(10),
  buttonRadius: DeviceUiInfo.moderateScale(4),
  section: DeviceUiInfo.moderateScale(25),
  baseMargin: DeviceUiInfo.moderateScale(10),
  doubleBaseMargin: DeviceUiInfo.moderateScale(20),
  smallMargin: DeviceUiInfo.moderateScale(5),
  doubleSection: DeviceUiInfo.moderateScale(50),
  horizontalLineHeight: DeviceUiInfo.moderateScale(1),
  searchBarHeight: DeviceUiInfo.moderateScale(30),
  screenWidth: width < height ? width : height,
  screenHeight: width < height ? height : width,
  navBarHeight:
    Platform.OS === 'ios'
      ? DeviceUiInfo.moderateScale(45)
      : DeviceUiInfo.moderateScale(45),
  bottomTabBarHeight: DeviceUiInfo.isIphoneX
    ? DeviceUiInfo.moderateScale(190)
    : DeviceUiInfo.moderateScale(140),
  tabBarPaddingBottom: DeviceUiInfo.isIphoneX
    ? {paddingBottom: DeviceUiInfo.moderateScale(160)}
    : {
        paddingBottom:
          DeviceUiInfo.moderateScale(100) +
          DeviceUiInfo.moderateScale(statusBarHeight),
      },
  customNavBarPaddingTop: DeviceUiInfo.isIphoneX
    ? {marginTop: DeviceUiInfo.moderateScale(100)}
    : DeviceUiInfo.isIphone
    ? {
        marginTop: DeviceUiInfo.moderateScale(70 + StatusBar.currentHeight),
      }
    : {
        marginTop: DeviceUiInfo.moderateScale(60 + StatusBar.currentHeight),
      },
  customNavBarMarginTop: DeviceUiInfo.isIphoneX
    ? DeviceUiInfo.moderateScale(55)
    : DeviceUiInfo.isIphone
    ? DeviceUiInfo.moderateScale(50)
    : DeviceUiInfo.moderateScale(65 + StatusBar.currentHeight),
  pagePaddingHorizontal: DeviceUiInfo.moderateScale(15),
  largePagePaddingHorizontal: DeviceUiInfo.moderateScale(20),
  cardHeight: DeviceUiInfo.moderateScale(60),
  icons: {
    tiny: DeviceUiInfo.moderateScale(15),
    small: DeviceUiInfo.moderateScale(20),
    medium: DeviceUiInfo.moderateScale(30),
    large: DeviceUiInfo.moderateScale(45),
    xl: DeviceUiInfo.moderateScale(50),
  },
  images: {
    small: DeviceUiInfo.moderateScale(20),
    medium: DeviceUiInfo.moderateScale(40),
    large: DeviceUiInfo.moderateScale(60),
    logo: DeviceUiInfo.moderateScale(200),
  },
  size: {
    s50: DeviceUiInfo.moderateScale(50),
    s90: DeviceUiInfo.moderateScale(90),
  },
  paddings: {
    p0: {padding: DeviceUiInfo.moderateScale(0)},
    p5: {padding: DeviceUiInfo.moderateScale(5)},
    p10: {padding: DeviceUiInfo.moderateScale(10)},
    p12: {padding: DeviceUiInfo.moderateScale(12)},
    p15: {padding: DeviceUiInfo.moderateScale(15)},
    p20: {padding: DeviceUiInfo.moderateScale(20)},
    p25: {padding: DeviceUiInfo.moderateScale(25)},
    p30: {padding: DeviceUiInfo.moderateScale(30)},
    pL0: {paddingLeft: DeviceUiInfo.moderateScale(0)},
    pL5: {paddingLeft: DeviceUiInfo.moderateScale(5)},
    pL7: {paddingLeft: DeviceUiInfo.moderateScale(7)},
    pL10: {paddingLeft: DeviceUiInfo.moderateScale(10)},
    pL12: {paddingLeft: DeviceUiInfo.moderateScale(12)},
    pL15: {paddingLeft: DeviceUiInfo.moderateScale(15)},
    pL18: {paddingLeft: DeviceUiInfo.moderateScale(18)},
    pL20: {paddingLeft: DeviceUiInfo.moderateScale(20)},
    pL25: {paddingLeft: DeviceUiInfo.moderateScale(25)},
    pL30: {paddingLeft: DeviceUiInfo.moderateScale(30)},
    pR0: {paddingRight: 0},
    pR5: {paddingRight: DeviceUiInfo.moderateScale(5)},
    pR10: {paddingRight: DeviceUiInfo.moderateScale(10)},
    pR12: {paddingRight: DeviceUiInfo.moderateScale(12)},
    pR15: {paddingRight: DeviceUiInfo.moderateScale(15)},
    pR18: {paddingRight: DeviceUiInfo.moderateScale(18)},
    pR20: {paddingRight: DeviceUiInfo.moderateScale(20)},
    pR24: {paddingRight: DeviceUiInfo.moderateScale(24)},
    pR25: {paddingRight: DeviceUiInfo.moderateScale(25)},
    pR30: {paddingRight: DeviceUiInfo.moderateScale(30)},
    pT0: {paddingTop: 0},
    pT5: {paddingTop: DeviceUiInfo.moderateScale(5)},
    pT8: {paddingTop: DeviceUiInfo.moderateScale(8)},
    pT10: {paddingTop: DeviceUiInfo.moderateScale(10)},
    pT15: {paddingTop: DeviceUiInfo.moderateScale(15)},
    pT16: {paddingTop: DeviceUiInfo.moderateScale(16)},
    pT20: {paddingTop: DeviceUiInfo.moderateScale(20)},
    pT25: {paddingTop: DeviceUiInfo.moderateScale(25)},
    pT30: {paddingTop: DeviceUiInfo.moderateScale(30)},
    pB0: {paddingBottom: 0},
    pB5: {paddingBottom: DeviceUiInfo.moderateScale(5)},
    pB10: {paddingBottom: DeviceUiInfo.moderateScale(10)},
    pB15: {paddingBottom: DeviceUiInfo.moderateScale(15)},
    pB20: {paddingBottom: DeviceUiInfo.moderateScale(20)},
    pB24: {paddingBottom: DeviceUiInfo.moderateScale(24)},
    pB25: {paddingBottom: DeviceUiInfo.moderateScale(25)},
    pB30: {paddingBottom: DeviceUiInfo.moderateScale(30)},
    pB50: {paddingBottom: DeviceUiInfo.moderateScale(50)},
    pB75: {paddingBottom: DeviceUiInfo.moderateScale(75)},
    pB85: {paddingBottom: DeviceUiInfo.moderateScale(85)},
    pB100: {paddingBottom: DeviceUiInfo.moderateScale(100)},
    pH0: {paddingHorizontal: 0},
    pH5: {paddingHorizontal: DeviceUiInfo.moderateScale(5)},
    pH10: {paddingHorizontal: DeviceUiInfo.moderateScale(10)},
    pH15: {paddingHorizontal: DeviceUiInfo.moderateScale(15)},
    pH16: {paddingHorizontal: DeviceUiInfo.moderateScale(16)},
    pH18: {paddingHorizontal: DeviceUiInfo.moderateScale(18)},
    pH20: {paddingHorizontal: DeviceUiInfo.moderateScale(20)},
    pH25: {paddingHorizontal: DeviceUiInfo.moderateScale(25)},
    pH30: {paddingHorizontal: DeviceUiInfo.moderateScale(30)},
    pH32: {paddingHorizontal: DeviceUiInfo.moderateScale(32)},
    pH35: {paddingHorizontal: DeviceUiInfo.moderateScale(35)},
    pH40: {paddingHorizontal: DeviceUiInfo.moderateScale(40)},
    pH45: {paddingHorizontal: DeviceUiInfo.moderateScale(45)},
    pV0: {paddingVertical: 0},
    pV3: {paddingVertical: DeviceUiInfo.moderateScale(3)},
    pV5: {paddingVertical: DeviceUiInfo.moderateScale(5)},
    pV8: {paddingVertical: DeviceUiInfo.moderateScale(8)},
    pV10: {paddingVertical: DeviceUiInfo.moderateScale(10)},
    pV15: {paddingVertical: DeviceUiInfo.moderateScale(15)},
    pV20: {paddingVertical: DeviceUiInfo.moderateScale(20)},
    pV25: {paddingVertical: DeviceUiInfo.moderateScale(25)},
    pV30: {paddingVertical: DeviceUiInfo.moderateScale(30)},
  },
  margins: {
    m0: {margin: 0},
    m5: {margin: DeviceUiInfo.moderateScale(5)},
    m10: {margin: DeviceUiInfo.moderateScale(10)},
    m15: {margin: DeviceUiInfo.moderateScale(15)},
    m20: {margin: DeviceUiInfo.moderateScale(20)},
    m25: {margin: DeviceUiInfo.moderateScale(25)},
    m30: {margin: DeviceUiInfo.moderateScale(30)},
    mL0: {marginLeft: 0},
    mL5: {marginLeft: DeviceUiInfo.moderateScale(5)},
    mL6: {marginLeft: DeviceUiInfo.moderateScale(6)},
    mL8: {marginLeft: DeviceUiInfo.moderateScale(8)},
    mL10: {marginLeft: DeviceUiInfo.moderateScale(10)},
    mL12: {marginLeft: DeviceUiInfo.moderateScale(12)},
    mL13: {marginLeft: DeviceUiInfo.moderateScale(13)},
    mL14: {marginLeft: DeviceUiInfo.moderateScale(14)},
    mL15: {marginLeft: DeviceUiInfo.moderateScale(15)},
    mL16: {marginLeft: DeviceUiInfo.moderateScale(16)},
    mL20: {marginLeft: DeviceUiInfo.moderateScale(20)},
    mL25: {marginLeft: DeviceUiInfo.moderateScale(25)},
    mL30: {marginLeft: DeviceUiInfo.moderateScale(30)},
    mR0: {marginRight: DeviceUiInfo.moderateScale(0)},
    mR5: {marginRight: DeviceUiInfo.moderateScale(5)},
    mR6: {marginLeft: DeviceUiInfo.moderateScale(6)},
    mR8: {marginLeft: DeviceUiInfo.moderateScale(8)},
    mR10: {marginRight: DeviceUiInfo.moderateScale(10)},
    mR15: {marginRight: DeviceUiInfo.moderateScale(15)},
    mR20: {marginRight: DeviceUiInfo.moderateScale(20)},
    mR25: {marginRight: DeviceUiInfo.moderateScale(25)},
    mR30: {marginRight: DeviceUiInfo.moderateScale(30)},
    mT0: {marginTop: DeviceUiInfo.moderateScale(0)},
    mT4: {marginTop: DeviceUiInfo.moderateScale(4)},
    mT5: {marginTop: DeviceUiInfo.moderateScale(5)},
    mT9: {marginTop: DeviceUiInfo.moderateScale(9)},
    mT10: {marginTop: DeviceUiInfo.moderateScale(10)},
    mT12: {marginTop: DeviceUiInfo.moderateScale(12)},
    mT14: {marginTop: DeviceUiInfo.moderateScale(14)},
    mT15: {marginTop: DeviceUiInfo.moderateScale(15)},
    mT16: {marginTop: DeviceUiInfo.moderateScale(16)},
    mT20: {marginTop: DeviceUiInfo.moderateScale(20)},
    mT24: {marginTop: DeviceUiInfo.moderateScale(24)},
    mT25: {marginTop: DeviceUiInfo.moderateScale(25)},
    mT30: {marginTop: DeviceUiInfo.moderateScale(30)},
    mT31: {marginTop: DeviceUiInfo.moderateScale(31)},
    mT35: {marginTop: DeviceUiInfo.moderateScale(35)},
    mT40: {marginTop: DeviceUiInfo.moderateScale(40)},
    mT50: {marginTop: DeviceUiInfo.moderateScale(50)},
    mB0: {marginBottom: DeviceUiInfo.moderateScale(0)},
    mB5: {marginBottom: DeviceUiInfo.moderateScale(5)},
    mB10: {marginBottom: DeviceUiInfo.moderateScale(10)},
    mB12: {marginBottom: DeviceUiInfo.moderateScale(12)},
    mB15: {marginBottom: DeviceUiInfo.moderateScale(15)},
    mB16: {marginBottom: DeviceUiInfo.moderateScale(16)},
    mB17: {marginBottom: DeviceUiInfo.moderateScale(17)},
    mB20: {marginBottom: DeviceUiInfo.moderateScale(20)},
    mB21: {marginBottom: DeviceUiInfo.moderateScale(21)},
    mB25: {marginBottom: DeviceUiInfo.moderateScale(25)},
    mB30: {marginBottom: DeviceUiInfo.moderateScale(30)},
    mB40: {marginBottom: DeviceUiInfo.moderateScale(40)},
    mB70: {marginBottom: DeviceUiInfo.moderateScale(70)},
    mB90: {marginBottom: DeviceUiInfo.moderateScale(90)},
    mH0: {marginHorizontal: DeviceUiInfo.moderateScale(0)},
    mH5: {marginHorizontal: DeviceUiInfo.moderateScale(5)},
    mH10: {marginHorizontal: DeviceUiInfo.moderateScale(10)},
    mH15: {marginHorizontal: DeviceUiInfo.moderateScale(15)},
    mH20: {marginHorizontal: DeviceUiInfo.moderateScale(20)},
    mH25: {marginHorizontal: DeviceUiInfo.moderateScale(25)},
    mH30: {marginHorizontal: DeviceUiInfo.moderateScale(30)},
    mH31: {marginHorizontal: DeviceUiInfo.moderateScale(31)},
    mH32: {marginHorizontal: DeviceUiInfo.moderateScale(32)},
    mH50: {marginHorizontal: DeviceUiInfo.moderateScale(50)},
    mV0: {marginVertical: DeviceUiInfo.moderateScale(0)},
    mV5: {marginVertical: DeviceUiInfo.moderateScale(5)},
    mV10: {marginVertical: DeviceUiInfo.moderateScale(10)},
    mV15: {marginVertical: DeviceUiInfo.moderateScale(15)},
    mV20: {marginVertical: DeviceUiInfo.moderateScale(20)},
    mV25: {marginVertical: DeviceUiInfo.moderateScale(25)},
    mV30: {marginVertical: DeviceUiInfo.moderateScale(30)},
  },
};

export default metrics;
